update 2

diff --git a/.github/workflows/pipeline-vlocity-diff.yml b/.github/workflows/pipeline-vlocity-diff.yml
--- a/.github/workflows/pipeline-vlocity-diff.yml
+++ b/.github/workflows/pipeline-vlocity-diff.yml
@@ -51,31 +51,31 @@ jobs:
         uses: actions/checkout@v3
 
       # Read pr_num file
-      - name: Read vlocityDiff
-        id: get_vlocityDiff
-        run: |
-          vlocityDiff=$(cat ./vlocityDiff-2.txt)
-          echo "$vlocityDiff"
-          # vlocityDiff=$(sed -z 's/\n/\\n/g' ./vlocityDiff.txt)
-          # echo "outvlocityDiff=$vlocityDiff" >> $GITHUB_ENV
+      # - name: Read vlocityDiff
+      #   id: get_vlocityDiff
+      #   run: |
+      #     vlocityDiff=$(cat ./vlocityDiff-2.txt)
+      #     echo "$vlocityDiff"
+      #     # vlocityDiff=$(sed -z 's/\n/\\n/g' ./vlocityDiff.txt)
+      #     # echo "outvlocityDiff=$vlocityDiff" >> $GITHUB_ENV
 
       # Deploy the difference in vlocity folder to instance
-      - name: Run Maintenance Jobs
-        if: (steps.get_vlocityDiff.outcome == 'success')
-        run: |
-          # Use the exit status of the grep command as the condition in the if statement
-          if grep -Eq "EXIT CODE 0" ./vlocityDiff-2.txt; then
-            echo "::error::No Changes Detected"
-            exit 1
-          elif grep -Eq "vlocity/(Product2|Catalog)/.*" ./vlocityDiff-2.txt; then
-            # If the exit status of the grep command is 0 (true), execute this branch
-            echo "SUCCESS!!!"
-          elif ! grep -Eq "vlocity/(Product2|Catalog)/.*" ./vlocityDiff-2.txt; then
-            # If the exit status of the grep command is 0 (true), execute this branch
-            echo "::error::FAILED!!!"
-            # If the exit status of the grep command is non-zero (false), execute this branch
-            echo "::error::Maintenance jobs run was failed"
-          fi
+      # - name: Run Maintenance Jobs
+      #   if: (steps.get_vlocityDiff.outcome == 'success')
+      #   run: |
+      #     # Use the exit status of the grep command as the condition in the if statement
+      #     if grep -Eq "EXIT CODE 0" ./vlocityDiff-2.txt; then
+      #       echo "::error::No Changes Detected"
+      #       exit 1
+      #     elif grep -Eq "vlocity/(Product2|Catalog)/.*" ./vlocityDiff-2.txt; then
+      #       # If the exit status of the grep command is 0 (true), execute this branch
+      #       echo "SUCCESS!!!"
+      #     elif ! grep -Eq "vlocity/(Product2|Catalog)/.*" ./vlocityDiff-2.txt; then
+      #       # If the exit status of the grep command is 0 (true), execute this branch
+      #       echo "::error::FAILED!!!"
+      #       # If the exit status of the grep command is non-zero (false), execute this branch
+      #       echo "::error::Maintenance jobs run was failed"
+      #     fi
 
       # Clean up downloaded directories
       - name: Clean up step
