test2

diff --git a/.github/workflows/pipeline-vlocity-diff.yml b/.github/workflows/pipeline-vlocity-diff.yml
--- a/.github/workflows/pipeline-vlocity-diff.yml
+++ b/.github/workflows/pipeline-vlocity-diff.yml
@@ -57,6 +57,9 @@ jobs:
             echo "::error::FAILED!!!"
             # If the exit status of the grep command is non-zero (false), execute this branch
             echo "::error::Maintenance jobs run was failed"
+          elif grep -Eq "EXIT CODE 0" ./vlocityDiff-2.txt; the
+            echo "::error::No Changes Detected"
+            exit 1
           fi
 
       # Clean up downloaded directories
