optimise

diff --git a/.github/workflows/pipeline-vlocity-diff.yml b/.github/workflows/pipeline-vlocity-diff.yml
--- a/.github/workflows/pipeline-vlocity-diff.yml
+++ b/.github/workflows/pipeline-vlocity-diff.yml
@@ -35,6 +35,65 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
+      # Read pr_num file
+      - name: Read vlocityDiff
+        id: get_vlocityDiff
+        run: |
+          # vlocityDiff=$(cat ./vlocityDiff.txt)
+          vlocityDiff=$(sed -z 's/\n/\\n/g' ./vlocityDiff.txt)
+          echo "vlocityDiff"
+          echo "outvlocityDiff=$vlocityDiff" >> $GITHUB_ENV
+
+      # Deploy the difference in vlocity folder to instance
+      - name: Run Maintenance Jobs
+        if: (steps.get_vlocityDiff.outcome == 'success')
+        run: |
+          # Use the exit status of the grep command as the condition in the if statement
+          if grep -Eq "vlocity/(Product2|Catalog)/.*" ${{env.outvlocityDiff}}; then
+            # If the exit status of the grep command is 0 (true), execute this branch
+            ./vlocity/apex/CatalogAndProductJob.cls
+            if [ $? -eq 0 ]; then
+              ./vlocity/apex/ProductHierarchyMaintenanceJob.cls
+              if [ $? -eq 0 ]; then
+                ./vlocity/apex/ClearManagedPlatformCacheJob.cls
+                if [ $? -eq 0 ]; then
+                  ./vlocity/apex/RefreshPlatformCacheFullJob.cls
+                  if [ $? -eq 0 ]; then
+                    ./vlocity/apex/PopulateApiCacheJob.cls
+                  else
+                    # If the exit status of the grep command is non-zero (false), execute this branch
+                    echo "::error::Maintenance jobs run was failed"
+                  fi
+                else
+                  # If the exit status of the grep command is non-zero (false), execute this branch
+                  echo "::error::Maintenance jobs run was failed"
+                fi
+              else
+                # If the exit status of the grep command is non-zero (false), execute this branch
+                echo "::error::Maintenance jobs run was failed"
+              fi
+            else
+              # If the exit status of the grep command is non-zero (false), execute this branch
+              echo "::error::Maintenance jobs run was failed"
+            fi
+          else
+            # If the exit status of the grep command is non-zero (false), execute this branch
+            echo "::error::Maintenance jobs run was failed"
+          fi
+
+      # Clean up downloaded directories
+      - name: Clean up step
+        run: |
+          sudo rm -rf branch_name
+          sudo rm -rf deploy.json
+          sudo rm -rf nomenclatureErrorsReport
+          sudo rm -rf pr_num
+          sudo rm -rf sfdxScannerReport.html
+          sudo rm -rf srcToDeploy.zip
+          sudo rm -rf validate.json
+          sudo rm -rf describe.log
+          ls -la
+
       # Install required OS packages
 #       - name: Install OS dependencies
 #         run: |
@@ -63,23 +122,6 @@ jobs:
 #           echo "$HOME/sfdx/bin" >> $GITHUB_PATH
 #           echo The PATH is $GITHUB_PATH
 #           ~/sfdx/bin/sfdx version
-
-      # Checkout current repository
-      - name: Checkout repo
-        uses: actions/checkout@v3
-
-      # Clean up downloaded directories
-      - name: Clean up step
-        run: |
-          sudo rm -rf branch_name
-          sudo rm -rf deploy.json
-          sudo rm -rf nomenclatureErrorsReport
-          sudo rm -rf pr_num
-          sudo rm -rf sfdxScannerReport.html
-          sudo rm -rf srcToDeploy.zip
-          sudo rm -rf validate.json
-          sudo rm -rf describe.log
-          ls -la
 
       # Download worflow artifacts from Git2SF workflow
       # - name: Download workflow artifact
@@ -117,27 +159,19 @@ jobs:
       #     prnum=$(cat pr_num.txt)
       #     echo "$prnum"
       #     echo "outprnum=$prnum" >> $GITHUB_OUTPUT
-      # Read pr_num file
-      - name: Read vlocityDiff
-        id: get_vlocityDiff
-        run: |
-          # vlocityDiff=$(cat ./vlocityDiff.txt)
-          vlocityDiff=$(sed -z 's/\n/\\n/g' ./vlocityDiff.txt)
-          echo "vlocityDiff"
-          echo "outvlocityDiff=$vlocityDiff" >> $GITHUB_ENV
 
-      # Install Vlocity
-      - name: Install Vlocity
-        run: |
-          npm install --global vlocity
-          vlocity --version
+      # # Install Vlocity
+      # - name: Install Vlocity
+      #   run: |
+      #     npm install --global vlocity
+      #     vlocity --version
 
-      # Install Git
-      - name: Install Git
-        run: |
-          sudo apt update
-          sudo apt-get install -y git
-          git --version
+      # # Install Git
+      # - name: Install Git
+      #   run: |
+      #     sudo apt update
+      #     sudo apt-get install -y git
+      #     git --version
 
       # Store Auth URL
       # - name: Store the SFDX Auth URL
@@ -164,43 +198,6 @@ jobs:
       #       exit 1
       #     fi
 
-      # Deploy the difference in vlocity folder to instance
-      - name: Run Maintenance Jobs
-        if: (steps.get_vlocityDiff.outcome == 'success')
-        run: |
-          # Use the exit status of the grep command as the condition in the if statement
-          if grep -Eq "vlocity/(Product2|Catalog)/.*" env.outvlocityDiff; then
-            # If the exit status of the grep command is 0 (true), execute this branch
-            ./vlocity/apex/CatalogAndProductJob.cls
-            if [ $? -eq 0 ]; then
-              ./vlocity/apex/ProductHierarchyMaintenanceJob.cls
-              if [ $? -eq 0 ]; then
-                ./vlocity/apex/ClearManagedPlatformCacheJob.cls
-                if [ $? -eq 0 ]; then
-                  ./vlocity/apex/RefreshPlatformCacheFullJob.cls
-                  if [ $? -eq 0 ]; then
-                    ./vlocity/apex/PopulateApiCacheJob.cls
-                  else
-                    # If the exit status of the grep command is non-zero (false), execute this branch
-                    echo "::error::Maintenance jobs run was failed"
-                  fi
-                else
-                  # If the exit status of the grep command is non-zero (false), execute this branch
-                  echo "::error::Maintenance jobs run was failed"
-                fi
-              else
-                # If the exit status of the grep command is non-zero (false), execute this branch
-                echo "::error::Maintenance jobs run was failed"
-              fi
-            else
-              # If the exit status of the grep command is non-zero (false), execute this branch
-              echo "::error::Maintenance jobs run was failed"
-            fi
-          else
-            # If the exit status of the grep command is non-zero (false), execute this branch
-            echo "::error::Maintenance jobs run was failed"
-          fi
-
       # # Find comments in PR
       # - name: Find Comment
       #   uses: peter-evans/find-comment@v2
@@ -219,16 +216,3 @@ jobs:
       #     issue-number: ${{ steps.get_pr_num.outputs.outprnum }}
       #     body: |
       #       + Maintenance Jobs Completed :white_check_mark:
-
-      # Clean up downloaded directories
-      - name: Clean up step
-        run: |
-          sudo rm -rf branch_name
-          sudo rm -rf deploy.json
-          sudo rm -rf nomenclatureErrorsReport
-          sudo rm -rf pr_num
-          sudo rm -rf sfdxScannerReport.html
-          sudo rm -rf srcToDeploy.zip
-          sudo rm -rf validate.json
-          sudo rm -rf describe.log
-          ls -la
