update workflow

diff --git a/.github/workflows/pipeline-test-manual.yml b/.github/workflows/pipeline-test-manual.yml
--- a/.github/workflows/pipeline-test-manual.yml
+++ b/.github/workflows/pipeline-test-manual.yml
@@ -21,6 +21,7 @@ on:
         type: choice
         required: true
         options:
+        - None
         - CI
         - SIT
         - UAT
@@ -55,42 +56,6 @@ jobs:
     env:
       TARGET_ENVIRONMNET: ${{inputs.targetEnv}}
     steps:
-      # Save PR number in PR_RUN text file
-      - name: Save the PR number
-        if: ${{github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'}}
-        shell: bash
-        env:
-          PR_NUM: ${{ github.event.number }}
-        run: |
-          echo $PR_NUM > pr_num.txt
-
-      # Upload PR number
-      - name: Upload Artifact PR number
-        if: ${{github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'}}
-        uses: actions/upload-artifact@v3
-        with:
-          name: pr_num
-          path: ./pr_num.txt
-          retention-days: 15
-
-      # Save source branch of PR
-      - name: Save the source branch of Pull request
-        if: ${{github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'}}
-        shell: bash
-        env:
-          BRANCH_NAME: ${{ github.head_ref }}
-        run: |
-          echo $BRANCH_NAME > branch_name.txt
-
-      # Upload the source branch of Pull request
-      - name: Upload Artifact source branch of Pull request
-        if: ${{github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'}}
-        uses: actions/upload-artifact@v3
-        with:
-          name: branch_name
-          path: ./branch_name.txt
-          retention-days: 15
-
       # Checkout the current repository
       - name: Checkout Repository
         uses: actions/checkout@v3
@@ -111,19 +76,29 @@ jobs:
         with:
           node-version: "18"
 
-      # Install Git
-      - name: Install Git
+      # check env and branch
+      - name: Check branch and env
         run: |
-          sudo apt update
-          sudo apt-get install -y git
-          git --version
+          if [ "${{ github.event.inputs.environment }}" == "CI" ] && [ "${{ github.ref }}" != "refs/heads/develop" ]; then
+            echo "Error: CI environment can only be used with develop"
+            exit 1
+          elif [ "${{ github.event.inputs.environment }}" == "SIT" ] && [ "${{ github.ref }}" != "refs/heads/int" ]; then
+            echo "Error: SIT environment can only be used with int branch"
+            exit 1
+          elif [ "${{ github.event.inputs.environment }}" == "UAT" ] && [ "${{ github.ref }}" != "refs/heads/releases" ]; then
+            echo "Error: UAT environment can only be used with releases branch"
+            exit 1
+          elif [ "${{ github.event.inputs.environment }}" == "PROD" ] && [ "${{ github.ref }}" != "refs/heads/main" ]; then
+            echo "Error: PROD environment can only be used with main branch"
+            exit 1
+          fi
 
       # check env
       - name: Enviornment CHECK
         run: |
           # You can use different secrets from each environment and handle exceptions like this:
           if [ "${{ github.event.inputs.environment }}" == "CI" ]; then
-            echo "Using secrets from Test_Deploy environment: ${{ secrets.HELLO }}, ${{ secrets.WELCOME }}, ${{ secrets.DEPLOY }}"
+            echo "Using secrets from CI environment: ${{ secrets.HELLO }}, ${{ secrets.TEST_SECRET }}"
           elif [ "${{ github.event.inputs.environment }}" == "SIT" ]; then
             echo "Using secrets from SIT environment: ${{ secrets.HELLO2SIT }}, ${{ secrets.SIT }}"
           elif [ "${{ github.event.inputs.environment }}" == "UAT" ]; then
